### ISSUE TITLE
the PR action fails

### ISSUE THREAD

**Issue by Roger-luo** [julia-actions/julia-format#10]
I just noticed this is not working recently. Any idea how to fix this? https://github.com/QuantumBFS/Yao.jl/runs/424492657

![image](https://user-images.githubusercontent.com/8445510/73707583-fde16780-46c9-11ea-8765-dae6c4ae7a3e.png)

**Comment by Roger-luo** [comment]
the formatter action fails on all packages in QuantumBFS somehow..

**Comment by domluna** [comment]
it looks like there's a problem with python dependencies in the upstream repo, I've opened an issue there.

**Comment by domluna** [comment]
actually looks like it works now

**Comment by Roger-luo** [comment]
still fails? https://github.com/QuantumBFS/Yao.jl/actions/runs/34513855

do I need to update something?

**Comment by domluna** [comment]
oh I forgot to mention you'll have to copy changes from the new file https://github.com/julia-actions/julia-format/blob/master/workflows/format_pr.yml

**Comment by Roger-luo** [comment]
thanks! fixed now
