### ISSUE TITLE
Recommended workflow packaged as action? (deprecation unclear)

### ISSUE THREAD

**Issue by st--** [julia-actions/julia-format#15]
Hi @domluna, thanks for providing JuliaFormatter & this formatting workflow! HowI'm wondering what's the reason behind marking the example in the README as deprecated? The linked https://github.com/julia-actions/julia-format/blob/master/workflows/format_check.yml seems rather more messy to add to one's own GitHub Action workflows: are you planning to provide a "packaged" version again at all? Coming from the JuliaFormatter repo, it's quite confusing that there's just this terse deprecation note (and on first reading I did not even realize it applied to the example below). It might be helpful if JuliaFormatter's README linked directly to the format_check.yml (or perhaps even included it in its own repository as an example, instead of depending on a separate repo)?

**Comment by domluna** [comment]
@st-- I removed that section from the README - you're right in it's confusing having it there
