### ISSUE TITLE
Unable to resolve action `julia-actions/julia-format@v3`, unable to find version `v3`

### ISSUE THREAD

**Issue by bvdmitri** [julia-actions/julia-format#28]
It seems that the `v3` is not available, but is mentioned in the README as the correct way to configure the action?

**Comment by xlxs4** [comment]
@bvdmitri should probably be `v2`.
c.f. https://github.com/julia-actions/julia-format/pull/24, https://github.com/julia-actions/julia-format/releases

**Comment by bvdmitri** [comment]
the README [uses](https://github.com/julia-actions/julia-format/blob/be8e90b6b386d0dbcff7504ba067aa2cd96c5948/README.md?plain=1#L20) `v3` though

**Comment by musoke** [comment]
I agree that it's odd for the readme to refer to a version that doesn't exist yet. 
Not just in the example, but also in the warning about breaking changes in v3.

**Comment by hyrodium** [comment]
The version in the README was updated as described in https://github.com/julia-actions/julia-format/pull/27#issuecomment-2044784840.

@domluna Could you tag and release a new version?

**Comment by domluna** [comment]
@hyrodium added you to the project as a collaborator. at this point you're more knowledgeable about actions than i am.

**Comment by hyrodium** [comment]
Thank you for the invitation!
I have manually tagged `v3` and `v3.0.0`, and organized releases on this repository.
https://github.com/julia-actions/julia-format/releases/tag/v3.0.0
