### ISSUE TITLE
Run formatting if action would fail

### ISSUE THREAD

**Issue by saschatimme** [julia-actions/julia-format#7]
I think it would be nice to have an option to automatically run the formatting (and doing a commit) in the case that the action would fail.

**Comment by tkf** [comment]
FYI creating PR when the formatting fails on `master` is not so difficult:
https://github.com/tkf/MyPlayground.jl/blob/bf1b2a434f8ef876fea3d2d73c697c6198d4c8c7/.github/workflows/format-pr.yml

But I'm not sure how to commit back to a PR from a fork.

**Comment by domluna** [comment]
I have an example workflow of this now so gonna close this.
