### ISSUE TITLE
Error: Some files have not been formatted

### ISSUE THREAD

**Issue by Roger-luo** [julia-actions/julia-format#9]
I'm not sure why, but I just tried this github action and it errors, any idea? 

https://github.com/QuantumBFS/YaoBlocks.jl/runs/327666924

```jl
┌ Error: Some files have not been formatted !!!
src/routines.jl
└ @ Main /format.jl:111
##[error]Docker run failed with exit code 1
```

**Comment by domluna** [comment]
This checks if the files have been formatted. So it saying src/routines.jl
does not match a formatted version of it.

Perhaps you’re using different options from the defaults? If so you’ll have
to pass on as args in the workflow file

**Comment by domluna** [comment]
So doing a diff

I get 

```
227c227
<         @inbounds Ns[locs_raw .+ i] = ns
---
>         @inbounds Ns[locs_raw.+i] = ns
```

**Comment by Roger-luo** [comment]
oh I see. so this is just checking the format not formatting it automatically I guess?

**Comment by domluna** [comment]
Currently yes. I’m pretty github actions would allow us to make a pr to
format files though

**Comment by Roger-luo** [comment]
OK, thanks. I'll set it up in this way first then. Yeah it would be convenient to have an option to let actions submit some PRs, but just checking is fine as well

**Comment by domluna** [comment]
@Roger-luo I have a example of a workflow that creates a PR here https://github.com/domluna/test-format-pr/blob/master/.github/workflows/format_pr.yml
